<?php

namespace VF\SNPBundle\Entity;

/**
 * GardeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardeRepository extends \Doctrine\ORM\EntityRepository
{
    
}
